#pragma once

#define GHOST_ACCEL 8000
#define GHOST_DASH_ACCEL (10 * GHOST_ACCEL)
#define GHOST_FRICTION 0.7
#define GHOST_MAX_SPEED 45000
#define GHOST_DASH_COOLDOWN 1.0
#define GHOST_MIN_SPEED_FOR_DASH 10

#define GHOST_ACTION_RANGE 100

#define EVENT_ACTION_RANGE 150

#define CAMERA_SLOW_RATIO 0.25
#define CAMERA_CATCHUP_RATIO 3

#define MAP_BORDER_SIZE 16

#define TILE_SIZE 16
#define SPRITES_SCALE 4

#define BACKGROUND_COLOR Color{ 106, 101, 118, 255 }

#define GHOST_FLOAT_FREQUENCY 4
#define GHOST_FLOAT_AMPLITUDE 5

#define PERSON_FADE_DURATION 0.5

#define SCENE_TRANSITION_DURATION 1
