#pragma once

#define GHOST_ACCEL 6000
#define GHOST_DASH_ACCEL (GHOST_ACCEL * 7)
#define GHOST_FRICTION 0.7
#define GHOST_MAX_SPEED 15000
#define GHOST_DASH_COOLDOWN 1.0

#define CAMERA_SLOW_RATIO 0.25
#define CAMERA_CATCHUP_RATIO 2
