#pragma once

#define GHOST_ACCEL 6000
#define GHOST_DASH_ACCEL (GHOST_ACCEL * 7)
#define GHOST_FRICTION 0.7
#define GHOST_MAX_SPEED 15000
#define GHOST_DASH_COOLDOWN 1.0
#define GHOST_MIN_SPEED_FOR_DASH 10

#define GHOST_ACTION_RANGE 100

#define EVENT_ACTION_RANGE 150

#define CAMERA_SLOW_RATIO 0.25
#define CAMERA_CATCHUP_RATIO 2

#define MAP_BORDER_SIZE 10
